= POC Static Blacklist and Whitelist component
Dennis Van de Poel <dennis.vandepoel@embedit.cz>
April 2020
:toc:

This is a Proof-Of-Concept built to explore and flesh out the functionality
and -more importantly- the REST APIs for a component that would be responsible
for the core blacklist/whitelist functionality which currently exists in HomerDB.

NOTE: Going forward when the term Blacklist is used, it is meant to 
denote both blacklist and whitelist  


== Objective: HomerDB Decomposition 

The idea is to entirely remove blacklist logic from HomerDB and offer a 
clear path to migrate dependent logic/components. 


=== Some of the objectives of this POC

* Define robust and formally defined interfaces.
* Explore application of Open-Closed principle.
* Explore application of Authorization concepts using JWT.
* Support legacy blacklists:
** BlacklistPers_EMAIL
** BlacklistPers_PHONE
** BlacklistPers_CLIENT_NAME
** BlacklistPers_EMAIL
** BlacklistPers_IP_ADDRESS
* Develop component to be aware of Cloud Native Design Principles.
  Five NIST cloud characteristics are:
** On-demand self-service. A consumer can unilaterally provision computing capabilities
** Broad network access.
** Resource pooling.
** Rapid elasticity.
** Measured service. 
* Allow for distributed tracing
* Solve data provenance
* Test meta tag, in order to allow traces in production, and test
  configuration to prod export


=== Description of Blacklist Component _Core_ Responsibilities

.Blacklist provides the following services:
* REST APIs for use by clients with non-critical, low-volume queries
* EVENTS (KAFKA/RABBITMQ) for use by clients with critical, high volume queries
* Blacklist related business logic (e.g. Blacklist entry expiry, Blacklist entry maintenance)

.Blacklist component will hold answer to following questions:
* What is current blacklist status of a given entity (e.g. customer email address)?
* What was blacklist status of a given entity on a certain date?
* Who/What disabled/enabled blacklist status for a given entity?

== Draft of REST API structure

....
/
/Blacklist
  /Blacklist/{blacklistname}/
  /Blacklist/{blacklistname}/data/
  /Blacklist/{blacklistname}/schema/
  /Blacklist/{blacklistname}/query/
/Blacklist
   GET:  returns a list of available blacklists
   POST: creates new blacklist, based on the definition file in the 
         body of the request
  /Blacklist/{blacklistname}/
     GET:  returns the blacklist definition file
  /Blacklist/{blacklistname}/data/
     POST: if the body adheres to the schema, creates new blacklist entry
  /Blacklist/{blacklistname}/schema/
     GET:  returns the schema of the blacklist entry datastructure
  /Blacklist/{blacklistname}/query/?params...
     GET:  returns all blacklist entries matching parameter criteria  
  /Blacklist/{blacklistname}/query/current/
     GET:  returns all currently active items
  /Blacklist/{blacklistname}/query/current/?params
     GET:  returns all currently active items matching parameter criteria


/Whitelist
   GET:  returns a list of available whitelists
   POST: creates new whitelist, based on the definition file in the 
         body of the request
  /Whitelist/{whitelistname}/
     GET:  returns the whitelist definition file
  /Whitelist/{whitelistname}/data/
     POST: if the body adheres to the schema, creates new whitelist entry
  /Whitelist/{whitelistname}/schema/
     GET:  returns the schema of the whitelist entry datastructure
  /Whitelist/{whitelistname}/query/?params...
     GET:  returns all whitelist entries matching parameter criteria  
  /Whitelist/{whitelistname}/query/current/
     GET:  returns all currently active items
  /Whitelist/{whitelistname}/query/current/?params
     GET:  returns all currently active items matching parameter criteria



/Excel     //presents a view through excel of the blacklist data

  /Excel/Whitelist/{whitelistname}/
    POST: Takes the excel file, validates it, and executes for each entry
          a POST against /Whitelist/{whitelistname}/data/
  /Excel/Whitelist/{whitelistname}/template
    GET:  Returns an excel sheet with no data, but with relevant 
          field names
  /Excel/Whitelist/{whitelistname}/query/*
    GET:  Returns an excel sheet with the data returned by executing a get
          against /Whitelist/{whitelistname}/query/*

  /Excel/Blacklist/{blacklistname}/
    POST: Takes the excel file, validates it, and executes for each entry
          a POST against /Blacklist/{blacklistname}/data/
  /Excel/Blacklist/{blacklistname}/template
    GET:  Returns an excel sheet with no data, but with relevant 
          field names
  /Excel/Blacklist/{blacklistname}/query/*
    GET:  Returns an excel sheet with the data returned by executing a get
        against /Blacklist/{blacklistname}/query/*


/UI       //a simple html/css/js view of the blacklist data and actions
    GET: returns UI with list of all blacklists and whitelists

  /UI/Whitelist
    GET: returns list of all whitelists
  /UI/Blacklist
    GET: returns list of all blacklists
  /UI/Whitelist/{whitelistname}/ 
    GET: returns ui to perform crud operations on whitelist data
  /UI/Blacklist/{blacklistname}/
    GET: returns ui to perform crud operations on whitelist data

....

== Open points

1. Review AS IS whitelist overriding blacklist functionality, and
   amend API design of
2. Define strategy to allow (backward compatible) changes of the 
   (data structure) definitions
   

== List of potential Features
Below is a list potential features that the Blacklist component might offer. 

[NOTE]
====
The list below is similar to the output of a brainstorming session,
i.e. has not been validated and constitute no way Acceptance criteria
of the POC or final component.

The list is in no particular order.
====

  Feature: Allow a user to query if some entity is currently blacklisted
    An entity can be customer email address, phone number, bank account
    A user will need to have proper authorization

  Feature: Allow a user to submit a fuzzy query if some entity is blacklisted
    Fuzzy queries will be rate limited
    An entity can be customer email address, phone number, bank account
    A user will need to have proper authorization

  Feature: Allow a user to query if some entity was blacklisted in the past
    An entity can be customer email address, phone number, bank account
    A user will need to have proper authorization

  Feature: Allow a user to download an excel template file to perform mass-upload
    The excel template file will have some validations based on schema definition
    
  Feature: Allow an admin user to create a new blacklist
    The admin can define relevant JWT rules that govern CRUD actions
    The admin can extend the schema (with some limits)

As a user with admin privileges
I can create new blacklists


As a user with blacklist maintenance privileges
I can change the status of a blacklist item

== Ignore everything under this
  Feature: Some terse yet descriptive text of what is desired
    In order to realize a named business value
    As an explicit system actor
    I want to gain some beneficial outcome which furthers the goal

  Scenario: Some determinable business situation
    Given some precondition
      And some other precondition
     When some action by the actor
      And some other action
      And yet another action
     Then some testable outcome is achieved
      And something else we can check happens too


[plantuml]
----
Bob->Alice : hello
----

[source,ruby]
----
require 'sinatra' // 

get '/hi' do // <1>
  "Hello World!" // <2>
end
----

<1> URL mapping
<2> HTTP response body


[plantuml]
----
@startuml
package "Some Group" {
  HTTP - [First Component]
  [Another Component]
}
 
node "Other Groups" {
  FTP - [Second Component]
  [First Component] --> FTP
} 

cloud {
  [Example 1]
}


database "MySql" {
  folder "This is my folder" {
    [Folder 3]
  }
  frame "Foo" {
    [Frame 4]
  }
}


[Another Component] --> [Example 1]
[Example 1] --> [Folder 3]
[Folder 3] --> [Frame 4]
@enduml
----
